Task 4 done
anton-bannykh/intro17 pull request #121
Opened 2017-12-15 18:35 UTC by nsychev

2017-12-17 17:28 UTC, anton-bannykh requested changes
Почему пропали тесты на некорректный ввод?

2017-12-17 17:28 UTC, anton-bannykh commented
Напиши, пожалуйста, последовательность команд для сборки и запуска.
Что-то вроде `gradle.bat jar` и `java -jar <path>.jar`

2017-12-17 17:32 UTC, nsychev commented
> Почему пропали тесты на некорректный ввод?

[Вот же они](https://github.com/nsychev/intro17/blob/e79ee37a2aef54e49e6760243a5716a73de5fb87/cli/src/test/java/MainTest.java#L12), просто теперь при некорректном вводе пустой массив возвращается

> Напиши, пожалуйста, последовательность команд для сборки и запуска.

У меня `jar` не получается запускать, гугление не помогло (перепробовал пару методов, при всех не запускается, пишет, что не может найти класс `Sum`). Посмотрел пулл-реквесты у остальных, но в них тоже не запускается

2017-12-17 17:37 UTC, anton-bannykh commented
> Вот же они, просто теперь при некорректном вводе пустой массив возвращается
Вот только ты еще и поведение программы поменял. Не надо так

> Посмотрел пулл-реквесты у остальных, но в них тоже не запускается
Правильно, я ни у кого и не принял =)

2017-12-17 17:38 UTC, nsychev commented
> Вот только ты еще и поведение программы поменял. Не надо так

Обратно вернуть?

> Правильно, я ни у кого и не принял =)

Нет, есть один принятый, и в нём тоже jar не запускается :(

2017-12-17 17:41 UTC, anton-bannykh commented
> Обратно вернуть?

2017-12-17 17:42 UTC, anton-bannykh commented
> Нет, есть один принятый, и в нём тоже jar не запускается :(

Это я недосмотрел. Ничего, он тоже исправит

2017-12-17 17:45 UTC, anton-bannykh commented
Если, что, то можно искать что-то навроде вот этого https://stackoverflow.com/questions/13782013/can-gradle-jar-multiple-projects-into-one-jar

2017-12-17 17:46 UTC, nsychev commented
> Если, что, то можно искать что-то навроде вот этого https://stackoverflow.com/questions/13782013/can-gradle-jar-multiple-projects-into-one-jar

Я как раз только что нагуглил это :)

2017-12-17 18:27 UTC, nsychev commented
@anton-bannykh 

Вернул всё, как было, и научился запускать jar, делается вот так:
```
./gradlew jar
java -jar cli/build/libs/cli-1.0.jar [ARGS]
```

2017-12-24 19:20 UTC, merged

2017-12-24 19:21 UTC, anton-bannykh commented
:+1: