Task 3 done
anton-bannykh/intro17 pull request #28
Opened 2017-11-27 15:41 UTC by nsychev

- added method `getSumOrError`
- added `main` method to get command-line arguments
- all methods became `static`, otherwise it will not work
- added test for parsing errors

2017-11-27 15:41 UTC, nsychev commented
Я сделал [вот это](https://help.github.com/articles/configuring-a-remote-for-a-fork/), но, видимо, не помогло :(

2017-11-27 16:15 UTC, BrilZliaN commented
@nsychev я просто сношу весь проект и пересоздаю заново перед новым таском, затем делаю все по инструкции. Костыль, но работает.

2017-11-27 16:21 UTC, nsychev commented
@BrilZliaN ладно, в следующем таске так и сделаю

2017-11-27 17:01 UTC, anton-bannykh commented
@BrilZliaN o_O Ничего себе. Надо какой-то попроще костыль изобрести.

2017-11-27 17:03 UTC, anton-bannykh commented
Надо, наверно, делать не merge, а rebase на upstream. Тогда одинаковые коммиты схлопнутся

2017-11-27 17:06 UTC, nsychev commented
Это тоже не правда

https://help.github.com/articles/about-pull-request-merges/
> The rebase and merge behavior on GitHub deviates slightly from git rebase. Rebase and merge on GitHub will always update the committer information and create new commit SHAs, whereas git rebase outside of GitHub does not change the committer information when the rebase happens on top of an ancestor commit. For more information about git rebase, see the "Git rebase" chapter from the Pro Git book.

2017-11-27 17:15 UTC, nsychev commented
[На stackoverflow пишут](https://stackoverflow.com/questions/36487142/why-merged-pull-request-in-github-creates-duplicate-commit), что с помощью UI GitHub это сделать нельзя.

Это можно сделать через терминал человеку, имеющему write access в этот репозиторий

2017-11-27 17:15 UTC, anton-bannykh commented
@nsychev  что именно неправда? Ты попробовал сделать `git merge upstream/master` и коммиты, различающиеся только `commiter`-ом не схлопнулись?

2017-11-27 17:16 UTC, nsychev commented
А, всё, я не так прочитал комментарий

Я почему-то прочитал, что нужно нажать не "Merge", а "Rebase and merge" при принятии пулл реквеста)

2017-11-27 17:17 UTC, anton-bannykh commented
Не, если просто на другую кнопку нажать, то конечно не поможет.

2017-11-27 17:27 UTC, nsychev commented
> Надо, наверно, делать не merge, а rebase на upstream. Тогда одинаковые коммиты схлопнутся

Так, я видимо снова ничего не понял. Делаю вот это:
```
git remote add upstream https://github.com/anton-bannykh/intro17.git
git fetch upstream
git checkout nikita-sychev
git rebase upstream/master
```

Появляется конфликт, я отредактировал всё так, как в последнем коммите, делаю `git rebase --continue`, а он пишет

```
Applying: added two new tests
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

Видимо, что-то пошло не так

2017-11-27 17:27 UTC, nsychev commented
Понятно, что у меня ничего не добавилось, но я-то хочу схлопнуть коммиты, а ничего не происходит

2017-11-27 17:33 UTC, anton-bannykh commented
попробуй `git rebase --skip`

2017-11-27 18:00 UTC, nsychev commented
Короче, у меня там всё пообламывалось из-за того, что я сделал ещё два новых коммита.

Решил проблему так:
```
git checkout upstream/nikita-sychev
git cherry-pick 080b59
git cherry-pick fb493f
git checkout nikita-sychev
git reset --hard e76784d
git push --force origin nikita-sychev
```

080b59 и fb493f — хеши коммитов, которые я сделал для этого пулл-реквеста, а e76784d — последний хеш, который получился после cherry-pick

2017-11-27 18:14 UTC, nsychev commented
Кажется, можно было проще...

```
git checkout nikita-sychev
git rebase --onto upstream/nikita-sychev nikita-sychev~2 nikita-sychev
git push --force origin nikita-sychev
```

(но это не точно, так как я не пробовал)

2017-11-28 11:46 UTC, anton-bannykh requested changes
см. комменты

2017-11-28 11:46 UTC, anton-bannykh commented on src/test/java/MainTest.java
> +    assertEquals(String.format(ERROR_TEXT, 0), (new Main()).getSumOrError(new String[] {"a"}));
Тут лучше руками написать текст, это нагляднее.
Кроме того, считается плохим стилем вызывать статический метод на инстансе класса. Поэтому лучше просто `Main.getSumOrError(...`

2017-11-28 11:46 UTC, anton-bannykh commented on src/test/java/MainTest.java
> +    assertEquals("0", (new Main()).getSumOrError(new String[] {"1", "2", "-3"}));
Лучше разнести тест на ошибки и тест на успешное поведение.

2017-11-28 11:46 UTC, anton-bannykh commented on src/test/java/MainTest.java
> +    assertEquals(String.format(ERROR_TEXT, 0), (new Main()).getSumOrError(new String[] {"a"}));
И лучше добавить еще тест, когда позиция не нулевая.

2017-11-28 12:04 UTC, nsychev commented on src/test/java/MainTest.java
> +    assertEquals(String.format(ERROR_TEXT, 0), (new Main()).getSumOrError(new String[] {"a"}));
Если руками написать текст, то будет 116 символов и стайл-чекер начнет ругаться
Могу сделать `final static String ERROR_TEXT_1 = "... at position 0";` и `final static String ERROR_TEXT_2 = "... at position 5";` и их юзать, так хорошо?

2017-11-28 12:05 UTC, nsychev commented on src/test/java/MainTest.java
> +    assertEquals(String.format(ERROR_TEXT, 0), (new Main()).getSumOrError(new String[] {"a"}));
Насчет статических методов - я просто сначала сделал их обычными, а потом уже пришлось переделать в статические, т.к. надо из main вызывать, поправлю

2017-11-28 17:21 UTC, nsychev commented
@anton-bannykh готово

2017-11-29 11:46 UTC, anton-bannykh reviewed
В припципе и так норм

2017-11-29 11:46 UTC, anton-bannykh commented on src/test/java/MainTest.java
> +    assertEquals(ERROR_TEXT_2, Main.getSumOrError(new String[] {"0", "17", "34", "51", "hello"}));
Не надо выносить как константы. Какой смысл? Нигде больше не используется же. Наоборот, просто пишешь
`assertEquals("Cannot parse integer at position 0", ...`. Тогда при просмотре кода сразу понятно, что должно получаться. Для тестов чем нагляднее, тем лучше =)

2017-11-29 11:46 UTC, anton-bannykh commented on src/test/java/MainTest.java
> +    assertEquals(6, Main.sum(new int[] {1, 2, 3}));
можно тут тоже сделать static import, чтобы Main не писать постоянно

2017-11-29 11:47 UTC, merged