Task1
anton-bannykh/intro17 pull request #32
Opened 2017-11-27 17:17 UTC by Starcall

Добавил ненужные для коммитов файлы в .gitignore

2017-11-27 17:39 UTC, anton-bannykh commented
Напиши в commit message что-нибудь более содержательное =)

2017-11-27 17:42 UTC, Starcall commented
> https://github.com/Starcall/intro17.git
Как сделать новый commit message или редактирова старый, если ничего не хочется менять в проекте? Он не дает пустой коммит сделать

2017-11-27 17:45 UTC, anton-bannykh commented
git commit --amend -m "New commit message"
git push -f

2017-11-27 17:52 UTC, Starcall commented
Сделал

2017-11-27 18:48 UTC, Starcall commented
Упс, случайно закоммитил второе задание в первый pull request

2017-11-27 19:58 UTC, anton-bannykh commented
:-)

On Mon, Nov 27, 2017 at 21:48 Starcall <notifications@github.com> wrote:

> Упс, случайно закоммитил второе задание в первый pull request
>
> —
> You are receiving this because you commented.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/anton-bannykh/intro17/pull/32#issuecomment-347284535>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABEG4CTOihfp_Ceh9UmEVyw-GWZ90-aiks5s6wQAgaJpZM4Qr_M7>
> .
>

2017-11-27 20:05 UTC, Starcall commented
Так все, первое задание считается выполненным? и нужно ли создать второй пулл реквест для второго задания, если я его уже сюда закоммитил?

2017-11-27 20:11 UTC, anton-bannykh commented
Нужно. Извини, посмотрю и все проставлю завтра

On Mon, Nov 27, 2017 at 23:05 Starcall <notifications@github.com> wrote:

> Так все, первое задание считается выполненным? и нужно ли создать второй
> пулл реквест для второго задания, если я его уже сюда закоммитил?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/anton-bannykh/intro17/pull/32#issuecomment-347310316>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABEG4P6Gpa1fytlmOicyOZymaAyvRH8xks5s6xX-gaJpZM4Qr_M7>
> .
>

2017-11-28 11:01 UTC, anton-bannykh commented
Пожалуйста, сделай так, чтобы этот pull request содиржал только изменения по первому заданию

2017-11-28 11:44 UTC, anton-bannykh reviewed
Разбить на отдельные pull request-ы

2017-11-28 11:45 UTC, anton-bannykh requested changes
.

2017-11-29 16:27 UTC, Starcall commented
Я удалил ненужные коммиты!

2017-12-01 16:47 UTC, anton-bannykh commented
Извини, только сейчас руки дошли

2017-12-01 16:47 UTC, merged