Task 3
anton-bannykh/intro17 pull request #40
Opened 2017-11-27 19:20 UTC by BrilZliaN

2017-11-28 11:13 UTC, anton-bannykh requested changes

2017-11-28 11:13 UTC, anton-bannykh commented on src/main/java/Main.java
> +    int answer = this.sumPowersOf2(numbers);
тут `this` не нужен, это не JS =)

2017-11-28 11:13 UTC, anton-bannykh commented on src/main/java/Main.java
> +    System.out.println(that.sumPowersOf2(args));
Можно в одну строчку записать, но не обязательно.

2017-11-28 11:13 UTC, anton-bannykh commented on src/main/java/Main.java
> +    System.out.println(that.sumPowersOf2(args));
Или сделать все `static` - на твое усмотрение

2017-11-28 11:13 UTC, anton-bannykh commented on src/test/java/MainTest.java
> +  }
Тесты ок

2017-11-28 11:53 UTC, BrilZliaN commented on src/main/java/Main.java
> +    int answer = this.sumPowersOf2(numbers);
Ок, уберу, лень писать было, автодополнение

2017-11-28 16:29 UTC, BrilZliaN commented
Вроде готово.

2017-11-29 11:42 UTC, anton-bannykh commented
Все ок

2017-11-29 11:42 UTC, merged