Task 2
anton-bannykh/intro17 pull request #42
Opened 2017-11-27 19:41 UTC by Mervap

Resolve algorithm, tests, check codestile

2017-11-27 21:08 UTC, Mervap commented
Упс, я не думал что при коммите в свой форк Task3 он заменит Task2 тут

2017-11-28 11:22 UTC, anton-bannykh commented
Пожалуйста, сделай так, чтобы на задания 2 и 3 были разные pull request-ы (считай это частью проверки твоих навыков работы с Git-ом :-) )

2017-11-28 11:23 UTC, anton-bannykh requested changes
Надо разбить да 2 пулл реквеста

2017-11-28 13:47 UTC, Mervap commented
Откатил до Task 2

2017-11-28 13:59 UTC, Mervap commented
Откатил до Task 2

2017-11-29 11:35 UTC, anton-bannykh commented
Пожалуйста, сделай так, чтобы остался один коммит.

2017-11-29 17:41 UTC, closed without merging